//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero.Web.Manage.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ShoesNetSoap")]
    public interface ShoesNetSoap {
        
        // CODEGEN: 消息 GetBrandListRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBrandList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zero.Web.Manage.ServiceReference1.GetBrandListResponse GetBrandList(Zero.Web.Manage.ServiceReference1.GetBrandListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBrandList", ReplyAction="*")]
        System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetBrandListResponse> GetBrandListAsync(Zero.Web.Manage.ServiceReference1.GetBrandListRequest request);
        
        // CODEGEN: 消息 GetProductCountRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zero.Web.Manage.ServiceReference1.GetProductCountResponse GetProductCount(Zero.Web.Manage.ServiceReference1.GetProductCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductCount", ReplyAction="*")]
        System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetProductCountResponse> GetProductCountAsync(Zero.Web.Manage.ServiceReference1.GetProductCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zero.Web.Manage.ServiceReference1.GetProductListResponse GetProductList(Zero.Web.Manage.ServiceReference1.GetProductListRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductList", ReplyAction="*")]
        System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetProductListResponse> GetProductListAsync(Zero.Web.Manage.ServiceReference1.GetProductListRequest request);
        
        // CODEGEN: 消息 GetProductInfoRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Zero.Web.Manage.ServiceReference1.GetProductInfoResponse GetProductInfo(Zero.Web.Manage.ServiceReference1.GetProductInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetProductInfoResponse> GetProductInfoAsync(Zero.Web.Manage.ServiceReference1.GetProductInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ShoesNetSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string pwdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
                this.RaisePropertyChanged("Pwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int coloridField;
        
        private int productIDField;
        
        private int colorIDField;
        
        private string productNameField;
        
        private decimal marketPriceField;
        
        private decimal priceField;
        
        private string photoField;
        
        private string photo2Field;
        
        private string productIntroField;
        
        private string detailUrlField;
        
        private int visitsField;
        
        private string[] photoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int colorid {
            get {
                return this.coloridField;
            }
            set {
                this.coloridField = value;
                this.RaisePropertyChanged("colorid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("ProductID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ColorID {
            get {
                return this.colorIDField;
            }
            set {
                this.colorIDField = value;
                this.RaisePropertyChanged("ColorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal MarketPrice {
            get {
                return this.marketPriceField;
            }
            set {
                this.marketPriceField = value;
                this.RaisePropertyChanged("MarketPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
                this.RaisePropertyChanged("Photo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Photo2 {
            get {
                return this.photo2Field;
            }
            set {
                this.photo2Field = value;
                this.RaisePropertyChanged("Photo2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ProductIntro {
            get {
                return this.productIntroField;
            }
            set {
                this.productIntroField = value;
                this.RaisePropertyChanged("ProductIntro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DetailUrl {
            get {
                return this.detailUrlField;
            }
            set {
                this.detailUrlField = value;
                this.RaisePropertyChanged("DetailUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Visits {
            get {
                return this.visitsField;
            }
            set {
                this.visitsField = value;
                this.RaisePropertyChanged("Visits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public string[] PhotoList {
            get {
                return this.photoListField;
            }
            set {
                this.photoListField = value;
                this.RaisePropertyChanged("PhotoList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Brand : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int brandIdField;
        
        private string brandNameField;
        
        private string enBrandNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int BrandId {
            get {
                return this.brandIdField;
            }
            set {
                this.brandIdField = value;
                this.RaisePropertyChanged("BrandId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BrandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
                this.RaisePropertyChanged("BrandName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EnBrandName {
            get {
                return this.enBrandNameField;
            }
            set {
                this.enBrandNameField = value;
                this.RaisePropertyChanged("EnBrandName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBrandList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBrandListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader;
        
        public GetBrandListRequest() {
        }
        
        public GetBrandListRequest(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader) {
            this.ShoesNetSoapHeader = ShoesNetSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBrandListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBrandListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Zero.Web.Manage.ServiceReference1.Brand[] GetBrandListResult;
        
        public GetBrandListResponse() {
        }
        
        public GetBrandListResponse(Zero.Web.Manage.ServiceReference1.Brand[] GetBrandListResult) {
            this.GetBrandListResult = GetBrandListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductCount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductCountRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string brandName;
        
        public GetProductCountRequest() {
        }
        
        public GetProductCountRequest(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader, string brandName) {
            this.ShoesNetSoapHeader = ShoesNetSoapHeader;
            this.brandName = brandName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductCountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetProductCountResult;
        
        public GetProductCountResponse() {
        }
        
        public GetProductCountResponse(int GetProductCountResult) {
            this.GetProductCountResult = GetProductCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string brandName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pagesize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int page;
        
        public GetProductListRequest() {
        }
        
        public GetProductListRequest(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader, string brandName, int pagesize, int page) {
            this.ShoesNetSoapHeader = ShoesNetSoapHeader;
            this.brandName = brandName;
            this.pagesize = pagesize;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Zero.Web.Manage.ServiceReference1.ProductInfo[] GetProductListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int total;
        
        public GetProductListResponse() {
        }
        
        public GetProductListResponse(Zero.Web.Manage.ServiceReference1.ProductInfo[] GetProductListResult, int total) {
            this.GetProductListResult = GetProductListResult;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int productId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int colorId;
        
        public GetProductInfoRequest() {
        }
        
        public GetProductInfoRequest(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader, int productId, int colorId) {
            this.ShoesNetSoapHeader = ShoesNetSoapHeader;
            this.productId = productId;
            this.colorId = colorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Zero.Web.Manage.ServiceReference1.ProductInfo GetProductInfoResult;
        
        public GetProductInfoResponse() {
        }
        
        public GetProductInfoResponse(Zero.Web.Manage.ServiceReference1.ProductInfo GetProductInfoResult) {
            this.GetProductInfoResult = GetProductInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShoesNetSoapChannel : Zero.Web.Manage.ServiceReference1.ShoesNetSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShoesNetSoapClient : System.ServiceModel.ClientBase<Zero.Web.Manage.ServiceReference1.ShoesNetSoap>, Zero.Web.Manage.ServiceReference1.ShoesNetSoap {
        
        public ShoesNetSoapClient() {
        }
        
        public ShoesNetSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShoesNetSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoesNetSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoesNetSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zero.Web.Manage.ServiceReference1.GetBrandListResponse Zero.Web.Manage.ServiceReference1.ShoesNetSoap.GetBrandList(Zero.Web.Manage.ServiceReference1.GetBrandListRequest request) {
            return base.Channel.GetBrandList(request);
        }
        
        public Zero.Web.Manage.ServiceReference1.Brand[] GetBrandList(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader) {
            Zero.Web.Manage.ServiceReference1.GetBrandListRequest inValue = new Zero.Web.Manage.ServiceReference1.GetBrandListRequest();
            inValue.ShoesNetSoapHeader = ShoesNetSoapHeader;
            Zero.Web.Manage.ServiceReference1.GetBrandListResponse retVal = ((Zero.Web.Manage.ServiceReference1.ShoesNetSoap)(this)).GetBrandList(inValue);
            return retVal.GetBrandListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetBrandListResponse> Zero.Web.Manage.ServiceReference1.ShoesNetSoap.GetBrandListAsync(Zero.Web.Manage.ServiceReference1.GetBrandListRequest request) {
            return base.Channel.GetBrandListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetBrandListResponse> GetBrandListAsync(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader) {
            Zero.Web.Manage.ServiceReference1.GetBrandListRequest inValue = new Zero.Web.Manage.ServiceReference1.GetBrandListRequest();
            inValue.ShoesNetSoapHeader = ShoesNetSoapHeader;
            return ((Zero.Web.Manage.ServiceReference1.ShoesNetSoap)(this)).GetBrandListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zero.Web.Manage.ServiceReference1.GetProductCountResponse Zero.Web.Manage.ServiceReference1.ShoesNetSoap.GetProductCount(Zero.Web.Manage.ServiceReference1.GetProductCountRequest request) {
            return base.Channel.GetProductCount(request);
        }
        
        public int GetProductCount(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader, string brandName) {
            Zero.Web.Manage.ServiceReference1.GetProductCountRequest inValue = new Zero.Web.Manage.ServiceReference1.GetProductCountRequest();
            inValue.ShoesNetSoapHeader = ShoesNetSoapHeader;
            inValue.brandName = brandName;
            Zero.Web.Manage.ServiceReference1.GetProductCountResponse retVal = ((Zero.Web.Manage.ServiceReference1.ShoesNetSoap)(this)).GetProductCount(inValue);
            return retVal.GetProductCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetProductCountResponse> Zero.Web.Manage.ServiceReference1.ShoesNetSoap.GetProductCountAsync(Zero.Web.Manage.ServiceReference1.GetProductCountRequest request) {
            return base.Channel.GetProductCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetProductCountResponse> GetProductCountAsync(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader, string brandName) {
            Zero.Web.Manage.ServiceReference1.GetProductCountRequest inValue = new Zero.Web.Manage.ServiceReference1.GetProductCountRequest();
            inValue.ShoesNetSoapHeader = ShoesNetSoapHeader;
            inValue.brandName = brandName;
            return ((Zero.Web.Manage.ServiceReference1.ShoesNetSoap)(this)).GetProductCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zero.Web.Manage.ServiceReference1.GetProductListResponse Zero.Web.Manage.ServiceReference1.ShoesNetSoap.GetProductList(Zero.Web.Manage.ServiceReference1.GetProductListRequest request) {
            return base.Channel.GetProductList(request);
        }
        
        public Zero.Web.Manage.ServiceReference1.ProductInfo[] GetProductList(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader, string brandName, int pagesize, int page, out int total) {
            Zero.Web.Manage.ServiceReference1.GetProductListRequest inValue = new Zero.Web.Manage.ServiceReference1.GetProductListRequest();
            inValue.ShoesNetSoapHeader = ShoesNetSoapHeader;
            inValue.brandName = brandName;
            inValue.pagesize = pagesize;
            inValue.page = page;
            Zero.Web.Manage.ServiceReference1.GetProductListResponse retVal = ((Zero.Web.Manage.ServiceReference1.ShoesNetSoap)(this)).GetProductList(inValue);
            total = retVal.total;
            return retVal.GetProductListResult;
        }
        
        public System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetProductListResponse> GetProductListAsync(Zero.Web.Manage.ServiceReference1.GetProductListRequest request) {
            return base.Channel.GetProductListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zero.Web.Manage.ServiceReference1.GetProductInfoResponse Zero.Web.Manage.ServiceReference1.ShoesNetSoap.GetProductInfo(Zero.Web.Manage.ServiceReference1.GetProductInfoRequest request) {
            return base.Channel.GetProductInfo(request);
        }
        
        public Zero.Web.Manage.ServiceReference1.ProductInfo GetProductInfo(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader, int productId, int colorId) {
            Zero.Web.Manage.ServiceReference1.GetProductInfoRequest inValue = new Zero.Web.Manage.ServiceReference1.GetProductInfoRequest();
            inValue.ShoesNetSoapHeader = ShoesNetSoapHeader;
            inValue.productId = productId;
            inValue.colorId = colorId;
            Zero.Web.Manage.ServiceReference1.GetProductInfoResponse retVal = ((Zero.Web.Manage.ServiceReference1.ShoesNetSoap)(this)).GetProductInfo(inValue);
            return retVal.GetProductInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetProductInfoResponse> Zero.Web.Manage.ServiceReference1.ShoesNetSoap.GetProductInfoAsync(Zero.Web.Manage.ServiceReference1.GetProductInfoRequest request) {
            return base.Channel.GetProductInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zero.Web.Manage.ServiceReference1.GetProductInfoResponse> GetProductInfoAsync(Zero.Web.Manage.ServiceReference1.ShoesNetSoapHeader ShoesNetSoapHeader, int productId, int colorId) {
            Zero.Web.Manage.ServiceReference1.GetProductInfoRequest inValue = new Zero.Web.Manage.ServiceReference1.GetProductInfoRequest();
            inValue.ShoesNetSoapHeader = ShoesNetSoapHeader;
            inValue.productId = productId;
            inValue.colorId = colorId;
            return ((Zero.Web.Manage.ServiceReference1.ShoesNetSoap)(this)).GetProductInfoAsync(inValue);
        }
    }
}
